### ISSUE TITLE
click/black version incompatibility

### ISSUE THREAD

**Issue by JMMarchant** [grantmcconnaughey/Lintly#35]
`lintly` currently specifies `click<7` in its `setup.py` which makes it incompatible with the stable version of `black` which specifies `click>=7.1.2`.

**Comment by grantmcconnaughey** [comment]
Thanks for the heads up! I can double check that Lintly works with Click 7 and bump the version if so.

**Comment by grantmcconnaughey** [comment]
Fixed in #37
