### ISSUE TITLE
Using Lintly multiple times in one project

### ISSUE THREAD

**Issue by spockNinja** [grantmcconnaughey/Lintly#9]
Right now, Lintly posts a commit status as `Lintly` no matter what. We are planning on using Lintly to lint more than one command's output (cfn-lint and black). At the moment, only the last one to post is successfully displayed in GitHub.

If we could add some sort of `--context` flag to the command, and pass that down to the GitHubBackend, we could have multiple statuses in the same project.

Ideally, we could have a status for `Lintly/cfn-lint` and `Lintly/black` much like CodeCov does with `codecov/patch` and `codecov/project`.

Does this make sense, and would it be a welcome addition?

**Comment by grantmcconnaughey** [comment]
I think that's an excellent idea. It would definitely be welcome.

**Comment by grantmcconnaughey** [comment]
Fixed in #10
